### ISSUE TITLE
Do something graceful with unknown paths like /garbage/sdkjfh

### ISSUE THREAD

**Issue by cshih7** [quokkateam/quokka#20]

**Comment by whittlbc** [comment]
For now since we don't have a 404 page, we should just redirect any non-accounted-for paths to the home page

**Comment by atn34** [comment]
Sounds good. This redirect (and the eventual 404 page) should be implemented with react router I think. Right now nginx [1] is routing all unknown paths to index.html, but it does not issue a redirect or change the path. We could maybe do this with nginx, but we'd have to register all known routes with nginx and I'd rather avoid the duplication.

[1]: https://github.com/heroku/heroku-buildpack-static uses nginx

**Comment by whittlbc** [comment]
Okay, should be fine for the demo then. Can deal with adding a 404 page later.
