### ISSUE TITLE
I changed FAQ text on "FAQ.js" - not sure it worked?

### ISSUE THREAD

**Issue by cshih7** [quokkateam/quokka#77]
I committed a change to the master branch on FAQ.js to just update some text on the FAQ page. It looks to be reflected in the code, but even when I hard refresh on quokkachallenge.com, I don't see the text change. Was this the wrong place to edit the text?

**Comment by whittlbc** [comment]
It worked it just didn't deploy. Dealing with getting auto-deploys set back up after changing to a private repo.
